backend:
  name: git-gateway
  repo: Carms-dev/pathwaves
  branch: dev
  commit_messages:
    create: '[ADD][CMS] {{collection}} “{{slug}}”'
    update: '[UPD][CMS] {{collection}} “{{slug}}”'
    delete: '[REM][CMS] {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

local_backend: true

media_folder: static/assets
public_folder: /assets

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_files # multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, fr]

  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

collections:
  - name: home
    label: Home Page
    folder: content/home
    create: false
    delete: false
    i18n: true
    fields:
      - {label: Template Key, name: templateKey, widget: hidden, default: "homePage.js", i18n: duplicate}
      # - label: Test markdown
      #   name: test
      #   widget: markdown
      - {label: Page Title, name: title, widget: string, i18n: true}
      - label: Intro Section
        name: sectionIntro
        widget: object
        i18n: true
        collapsed: true
        fields:
          - label: Image
            name: img
            widget: object
            i18n: true
            fields:
              - {label: Image, name: image, widget: image, choose_url: false, i18n: duplicate}
              - {label: Image Alt Text, name: alt, widget: string, i18n: true}
          - {label: Header, name: header, widget: string, i18n: true}
          - {label: Description, name: description, widget: text, i18n: true}
          - label: Button
            name: button
            widget: object
            i18n: true
            collapsed: true
            fields:
              - {label: Link text, name: linkText, widget: string, i18n: true}
              - {label: URL, name: url, widget: string, i18n: true}
      - label: Second Section
        name: sectionSecond
        widget: object
        i18n: true
        collapsed: true
        fields:
          - label: Description
            name: description
            widget: markdown
            buttons: [code, bold, italic, link, bulleted-list, numbered-list, heading-three, heading-four]
            editor_components: []
            modes: [rich_text]
            minimal: true
            i18n: true
          - label: Image
            name: img
            widget: object
            i18n: true
            fields:
              - {label: Image, name: image, widget: image, choose_url: false, i18n: duplicate}
              - {label: Image Alt Text, name: alt, widget: string, i18n: true}

      - label: Third Section
        name: sectionThird
        widget: object
        i18n: true
        collapsed: true
        fields:
          - label: Description
            name: description
            widget: markdown
            buttons: [code, bold, italic, link, bulleted-list, numbered-list, heading-three, heading-four]
            editor_components: []
            modes: [rich_text]
            minimal: true
            i18n: true

      - label: Forth Section
        name: sectionForth
        widget: object
        i18n: true
        collapsed: true
        fields:
          - label: Left Component
            name: leftComponent
            widget: object
            i18n: true
            collapsed: true
            fields:
            - label: Description
              name: description
              widget: markdown
              buttons: [code, bold, italic, link, bulleted-list, numbered-list, heading-three, heading-four]
              editor_components: []
              modes: [rich_text]
              minimal: true
              i18n: true
            - label: Button
              name: button
              widget: object
              i18n: true
              collapsed: true
              fields:
                - {label: Link text, name: linkText, widget: string, i18n: true}
                - {label: URL, name: url, widget: string, i18n: true}
            - label: Image
              name: img
              widget: object
              i18n: true
              fields:
                - {label: Image, name: image, widget: image, choose_url: false, i18n: duplicate}
                - {label: Image Alt Text, name: alt, widget: string, i18n: true}

          - label: Right Component
            name: rightComponent
            widget: object
            i18n: true
            collapsed: true
            fields:
            - label: Description
              name: description
              widget: markdown
              buttons: [code, bold, italic, link, bulleted-list, numbered-list, heading-three, heading-four]
              editor_components: []
              modes: [rich_text]
              minimal: true
              i18n: true
            - label: Button
              name: button
              widget: object
              i18n: true
              collapsed: true
              fields:
                - {label: Link text, name: linkText, widget: string, i18n: true}
                - {label: URL, name: url, widget: string, i18n: true}
            - label: Image
              name: img
              widget: object
              i18n: true
              fields:
                - {label: Image, name: image, widget: image, choose_url: false, i18n: duplicate}
                - {label: Image Alt Text, name: alt, widget: string, i18n: true}

      - label: Fifth Section
        name: sectionFifth
        widget: object
        i18n: true
        collapsed: true
        fields:
          - {label: Header, name: header, widget: string, i18n: true}
          - label: Phases
            name: phases
            widget: list
            i18n: true
            summary: '{{fields.header}} - {{fields.date}}'
            fields:
              - {label: Header, name: header, widget: string, i18n: true}
              - {label: Date, name: date, widget: string, i18n: true}
              - {label: Description, name: description, widget: text, i18n: true}
          - {label: End Note, name: endNote, widget: text, i18n: true}
          - label: Image
            name: img
            widget: object
            i18n: true
            fields:
              - {label: Image, name: image, widget: image, choose_url: false, i18n: duplicate}
              - {label: Image Alt Text, name: alt, widget: string, i18n: true}

      - label: Sixth Section
        name: sectionSixth
        widget: object
        i18n: true
        collapsed: true
        fields:
          - label: Description
            name: description
            widget: markdown
            buttons: [code, bold, italic, link, bulleted-list, numbered-list, heading-three, heading-four]
            editor_components: []
            modes: [rich_text]
            minimal: true
            i18n: true
          - label: Button
            name: button
            widget: object
            i18n: true
            collapsed: true
            fields:
              - {label: Link text, name: linkText, widget: string, i18n: true}
              - {label: URL, name: url, widget: string, i18n: true}

      - label: About Section
        name: sectionAbout
        widget: object
        i18n: true
        collapsed: true
        fields:
          - {label: Description, name: description, widget: text, i18n: true}
          - label: Collaborators
            name: collaborators
            widget: list
            min: 1
            i18n: true
            summary: "{{name}} - {{url}}"
            fields:
            - {label: Name, name: name, widget: string, i18n: true}
            - {label: Description, name: description, widget: text, i18n: true}
            - {label: URL, name: url, widget: string, i18n: duplicate}
            - label: Logo
              name: logo
              widget: object
              i18n: true
              fields:
                - {label: Image, name: image, widget: image, choose_url: false, i18n: duplicate}
                - {label: Image Alt Text, name: alt, widget: string, i18n: true}
          - {label: Contact Text, name: contactText, widget: text, i18n: true}
          - {label: Contact Email, name: contactEmail, widget: text, i18n: duplicate}

  - name: survey
    label: Survey Page
    folder: content/survey
    create: false
    delete: false
    i18n: true
    fields:
      - {label: Template Key, name: templateKey, widget: hidden, default: "genericPage.js", i18n: duplicate}
      - {label: Page Title, name: title, widget: string, i18n: true}
      - label: Policy
        name: body
        widget: markdown
        buttons: [bold, italic, link, bulleted-list, numbered-list, heading-three, heading-four]
        editor_components: []
        modes: [rich_text]
        minimal: true
        i18n: true
      - label: Policy
        name: policy
        widget: markdown
        buttons: [bold, italic, link, bulleted-list, numbered-list, heading-three, heading-four]
        editor_components: []
        modes: [rich_text]
        minimal: true
        i18n: true
      - label: Options
        name: options
        widget: list
        min: 2
        max: 2
        i18n: true
        summary: "{{linkText}} - {{linkAddress}}"
        fields:
        - {label: Link Text, name: linkText, widget: string}
        - {label: "Internal Link?", name: isInterenal, widget: boolean, required: false}
        - {label: Link Address, name: linkAddress, widget: string}
      - {label: Thank You Note, name: endNote, widget: string, i18n: true}

  - name: fourOhFour
    label: 404 Page
    folder: content/fourOhFour
    create: false
    delete: false
    i18n: true
    fields:
      - {label: Template Key, name: templateKey, widget: hidden, default: "fourOhFourPage.js", i18n: duplicate}
      - {label: Page Title, name: title, widget: string, i18n: true}
      - {label: Header, name: header, widget: string, i18n: true}
      - {label: Link Text, name: linkText, widget: string, i18n: true}
      - label: Image
        name: img
        widget: object
        i18n: true
        fields:
          - {label: Image, name: image, widget: image, choose_url: false, i18n: duplicate}
          - {label: Image Alt Text, name: alt, widget: string, i18n: true}

  - name: siteSetting
    label: Site Setting
    folder: content/siteSetting
    create: false
    delete: false
    i18n: true
    fields:
      - {label: Site Title, name: title, widget: string, i18n: true}
      - {label: Site Description, name: description, widget: text, i18n: true}
      - label: Logo
        name: logo
        widget: object
        i18n: true
        fields:
          - {label: Image, name: image, widget: image, choose_url: false, i18n: duplicate}
          - {label: Image Alt Text, name: alt, widget: string, i18n: true}

      - label: Navigation
        name: nav
        widget: object
        i18n: true
        fields:
          - label: Button
            name: button
            widget: object
            i18n: true
            collapsed: true
            fields:
              - {label: Link text, name: linkText, widget: string, i18n: true}
              - {label: URL, name: url, widget: string, i18n: true}

      - label: "Footer (Contact)"
        name: footer
        widget: object
        i18n: true
        fields:
          - {label: Copyright To, name: copyright, widget: string, i18n: true}
          - label: Footer Links
            name: footerLinks
            widget: list
            min: 1
            max: 2
            i18n: true
            summary: "{{linkText}} - {{linkAddress}}"
            fields:
            - {label: Link Text, name: linkText, widget: string}
            - {label: "Internal Link?", name: isInterenal, widget: boolean, required: false}
            - {label: Link Address, name: linkAddress, widget: string}
